BLENDER = C:\Steam\steamapps\common\Blender\blender.exe
TM2020 = C:\Steam\steamapps\common\Trackmania\
TMUSERPATH = C:\Users\drunub\Documents\Trackmania2020

; Example for Linux
; BLENDER = /home/<username>/Downloads/blender-4.5.8-linux-x64/blender
; TM2020 = /home/<username>/.local/share/Steam/steamapps/common/Trackmania/
; TMUSERPATH = /home/<username>/.local/share/Steam/steamapps/compatdata/2225070/pfx/drive_c/users/steamuser/Documents/Trackmania/